### ISSUE TITLE
I want a common storage area.

### ISSUE THREAD

**Issue by Akira-Taniguchi** [LayerZero-Labs/LayerZero#2]
I want a general-purpose storage area at the endpoint where data can be shared across the chain.

example)
ILayerZeroEndpoint.setValue(bytes32 memory _key, bytes32 memory _value);

ILayerZeroEndpoint.getValue(bytes32 memory _key) view return (bytes32);

[Assumed Use]
I want to store the total value of the total supply of ERC20 tokens for all chains.

**Comment by Oni-giri** [comment]
This would need a sidechain or to choose a blockchain where to store the data. Since Layer0 does not have 1) and is chain agnostic, it would probably be better to have a template smart contract that you deploy to achieve this. 

Also, this would put you in charge of its security, which is probably better as a single point of failure isn't going to prop up adoption.

For your use, you may adopt a model with a chain that is in charge of the minting/total supply bookkeeping, and tokens linked to it deployed on other chains. Maybe this would be useful ? https://github.com/LayerZero-Labs/solidity-examples/blob/main/contracts/token/oft/extension/BasedOFT.sol

**Comment by Oni-giri** [comment]
> This would need a sidechain or to choose a blockchain where to store the data. Since Layer0 does not have 1) and is chain agnostic, it would probably be better to have a template smart contract that you deploy to achieve this.
> 
> Also, this would put you in charge of its security, which is probably better as a single point of failure isn't going to prop up adoption.
> 
> For your use, you may adopt a model with a chain that is in charge of the minting/total supply bookkeeping, and tokens linked to it deployed on other chains. Maybe this would be useful ? https://github.com/LayerZero-Labs/solidity-examples/blob/main/contracts/token/oft/extension/BasedOFT.sol

An improvement could be to have a contract or method in the OFT like "GetMetadata(bool fetch)", which would allow you to fetch the value, either from the local storage, or the origin chain. If you're interested in this solution, I can look into it.

**Comment by Akira-Taniguchi** [comment]
ok, thanks
